spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Mc dn 5124 !
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 9000
    refreshTokenExpiration: 604800
